const MSG=`Olá, {NOME}! 👋\n\nA Eletropel tem uma novidade muito especial para você! 🎉\n\nEstamos inaugurando nossa nova filial em Rio Verde/GO e queremos convidar você para estar conosco nesse momento.\n\n📅 07/10 — quarta-feira\n🕘 Às 9h\n📍 Av. Presidente Vargas, nº 3027\nQD 44 • LT 04 • Vila Maria — Rio Verde/GO\n\nVocê é nosso convidado especial!\n\nEsperamos você! ❤️💛\n\nEletropel — Distribuidora de Auto Peças\n📲 (64) 3050-9700`;
let clients=JSON.parse(localStorage.getItem('eletropel_clients')||'[]'), current=-1;
const $=id=>document.getElementById(id); function save(){localStorage.setItem('eletropel_clients',JSON.stringify(clients));render()}
function cleanPhone(v){let d=String(v??'').replace(/\D/g,''); if(d.length===10||d.length===11)d='55'+d; return d}
function msg(c){return MSG.replace('{NOME}',c.name||'cliente')}
function render(){let total=clients.length,p=clients.filter(x=>x.status==='PENDENTE'||x.status==='EM_ATENDIMENTO').length,s=clients.filter(x=>x.status==='ENVIADO').length,e=clients.filter(x=>x.status==='ERRO').length;$('total').textContent=total;$('pending').textContent=p;$('sent').textContent=s;$('errors').textContent=e;if(current>=0&&clients[current])show();else{$('name').textContent=total?'Selecione um cliente':'Nenhum cliente carregado';$('phone').textContent='—';$('message').value=''};let q=$('search').value.toLowerCase();$('list').innerHTML=clients.map((c,i)=>({c,i})).filter(o=>`${o.c.name} ${o.c.phone}`.toLowerCase().includes(q)).slice(0,150).map(o=>`<div class="row" data-i="${o.i}"><div><b>${esc(o.c.name)}</b><br><small>${esc(o.c.phone)}</small></div><div class="status ${o.c.status}">${o.c.status}</div><div></div></div>`).join('');document.querySelectorAll('.row').forEach(r=>r.onclick=()=>select(+r.dataset.i));let done=s+e; $('bar').style.width=total?(done/total*100)+'%':'0%';$('progressText').textContent=`${done} / ${total}`}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function show(){let c=clients[current];$('name').textContent=c.name||'Cliente';$('phone').textContent=c.phone;$('message').value=msg(c);c.status='EM_ATENDIMENTO';saveNoRender()}
function saveNoRender(){localStorage.setItem('eletropel_clients',JSON.stringify(clients))}
function select(i){current=i;show();render()}
function next(){let i=clients.findIndex(x=>x.status==='PENDENTE');if(i<0)i=clients.findIndex(x=>x.status==='ERRO');if(i<0){alert('Não há mais clientes pendentes.');return}current=i;show();render();openWhatsApp()}
function openWhatsApp(){if(current<0)return;let c=clients[current],url=`https://wa.me/${c.phone}?text=${encodeURIComponent(msg(c))}`;window.open(url,'_blank')}
$('open').onclick=openWhatsApp;$('sentBtn').onclick=()=>{if(current<0)return;clients[current].status='ENVIADO';clients[current].sentAt=new Date().toISOString();let old=current;save();let i=clients.findIndex((x,j)=>j>old&&x.status==='PENDENTE');if(i<0)i=clients.findIndex(x=>x.status==='PENDENTE');if(i>=0)select(i)};$('skipBtn').onclick=()=>{if(current<0)return;clients[current].status='ERRO';save();next()};$('search').oninput=render;
$('file').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let data=await f.arrayBuffer(),wb=XLSX.read(data,{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{defval:''});let out=rows.map(r=>{let keys=Object.keys(r),nameKey=keys.find(k=>/nome|raz[aã]o social|fantasia|cliente/i.test(k)),phoneKey=keys.find(k=>/telefone|celular|whatsapp|fone|phone/i.test(k));return{name:String(r[nameKey||keys[0]]||'').trim(),phone:cleanPhone(r[phoneKey||keys[1]]),status:'PENDENTE'}}).filter(x=>x.phone.length>=12);let seen=new Set();out=out.filter(x=>!seen.has(x.phone)&&(seen.add(x.phone),true));clients=out;current=-1;save();alert(`${out.length} clientes carregados.`)}catch(err){alert('Não consegui ler o arquivo: '+err.message)}};
render();
